# Generated by Django 3.1.7 on 2021-04-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_auth', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='service_auth.student'),
        ),
        migrations.AddField(
            model_name='media',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='service_auth.Student'),
        ),
        migrations.AddField(
            model_name='case',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.answer'),
        ),
        migrations.AddField(
            model_name='case',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
        migrations.AddField(
            model_name='answer',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.case'),
        ),
    ]
