# Generated by Django 3.1.12 on 2021-06-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210620_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
