# Generated by Django 3.1.7 on 2021-06-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210607_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='course',
        ),
        migrations.AddField(
            model_name='media',
            name='lesson',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='file', to='core.lesson'),
        ),
    ]
