# Generated by Django 3.1.12 on 2021-06-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210620_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='core.course'),
        ),
    ]
