# Generated by Django 3.1.7 on 2021-04-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210415_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('PDF', 'Pdf'), ('VIDEO', 'Video')], default='PDF', max_length=10),
        ),
    ]
