# Generated by Django 3.1.12 on 2021-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210624_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='test_result',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='current_lesson',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='current_test',
            field=models.SmallIntegerField(default=1),
        ),
    ]
