# Generated by Django 3.1.12 on 2021-07-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210625_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.test'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to='core.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course'),
        ),
        migrations.AlterField(
            model_name='media',
            name='lesson',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.course'),
        ),
    ]
