# Generated by Django 3.1.7 on 2021-06-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210607_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.TextField(default='empty', max_length=128),
        ),
    ]
