# Generated by Django 3.1.7 on 2021-05-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210504_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
