# Generated by Django 3.1.12 on 2021-08-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210713_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='finish',
        ),
    ]
