# Generated by Django 3.1.12 on 2021-09-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_courseprogress_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='Урок', max_length=100),
        ),
    ]
