# Generated by Django 3.1.7 on 2021-06-02 04:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lesson_lesson_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
        migrations.AddField(
            model_name='media',
            name='body',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to=core.models.upload_to),
        ),
    ]
