# Generated by Django 3.1.7 on 2021-06-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_auth', '0002_auto_20210604_0550'),
        ('core', '0008_auto_20210602_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_passed', models.BooleanField(default=False)),
                ('current_lesson', models.SmallIntegerField(default=0)),
                ('current_test', models.SmallIntegerField(default=0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='service_auth.student')),
            ],
        ),
    ]
