# Generated by Django 3.1.7 on 2021-06-05 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_courseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='student',
        ),
        migrations.RemoveField(
            model_name='test',
            name='success',
        ),
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(default=uuid.UUID('8145aa04-6eef-494c-8088-8c57bed7abf8'), on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.TextField(default='?', max_length=1024),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.test'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=1024, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
