# Generated by Django 3.1.7 on 2021-06-05 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210605_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(default=uuid.UUID('09b81230-25e5-4bce-b46e-eb6e7f7ea654'), on_delete=django.db.models.deletion.DO_NOTHING, to='core.course'),
        ),
    ]
