# Generated by Django 3.1.7 on 2021-06-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='empty', max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Город'),
        ),
    ]
