# Generated by Django 3.1.12 on 2021-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_auth', '0002_auto_20210624_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='control',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='-', max_length=64, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='student',
            name='job',
            field=models.TextField(default='-', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='-', max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='place',
            field=models.TextField(default='-', verbose_name='Место работы'),
        ),
    ]
