# Generated by Django 3.1.7 on 2021-06-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_auth', '0002_auto_20210604_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='job',
            field=models.TextField(default='empty', verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.TextField(default='empty', verbose_name='Должность'),
        ),
    ]
